### ISSUE TITLE
[Memes] Unable to Handle UTF-8 text messages properly

### ISSUE THREAD

**Issue by rupansh** [rupansh/nim-tg-manager#2]
I don't have much idea about how to fix it. Just added a filter to verify the strings that are being sent.

Could be TeleBot api related but unsure

**Comment by imsk17** [comment]
Nu Idea, Dumb Langwez Prolly

**Comment by rupansh** [comment]
mock still needs fixing

**Comment by rupansh** [comment]
Problem with my windows locale.

**Comment by imsk17** [comment]
Wah Yr!
Gazab Time Barbaad Kia

**Comment by rupansh** [comment]
> Wah Yr!
> Gazab Time Barbaad Kia

ree
