### ISSUE TITLE
I tried to run the bot on my computer, but something went wrong trying to interact with the bot on Telegram 

### ISSUE THREAD

**Issue by tedescolor** [rupansh/nim-tg-manager#4]
Nim TG Bot is Up!
utils.nim(195)           makeRequestIter
utils.nim(187)           makeRequestIter
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
???                      ourProc2Iter
asyncfutures.nim(372)    read
asyncfutures.nim(420)    asyncCheckCallback
Error: unhandled exception: Bad Request: chat not found [IOError]
oserr.nim(94)            raiseOSError

**Comment by rupansh** [comment]
> Nim TG Bot is Up!
> utils.nim(195) makeRequestIter
> utils.nim(187) makeRequestIter
> asyncfutures.nim(372) read
> asyncfutures.nim(372) read
> ??? ourProc2Iter
> asyncfutures.nim(372) read
> asyncfutures.nim(420) asyncCheckCallback
> Error: unhandled exception: Bad Request: chat not found [IOError]
> oserr.nim(94) raiseOSError

Hi sorry I missed the issue from notifications! I will investigate the issue in a bit.

**Comment by rupansh** [comment]
Hi I am not getting this specific error when I am trying the bot. Can you send your config.ini(with token censored of course)

**Comment by rupansh** [comment]
closed due to inactivity.
My guess is invalid dump channel in config
